version: "3"

services:
  redis:
    image: redis:alpine
    restart: always

  front:
    image: mailu/nginx:1.9
    restart: always
    environment:
      TZ: Asia/Jerusalem
    depends_on:
      - resolver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailu.rule=Host(`mail.dorbenabu.com`)"
      - "traefik.http.routers.mailu.entrypoints=web"
      - "traefik.http.services.mailu.loadbalancer.server.port=80"

  admin:
    image: mailu/admin:1.9
    restart: always
    environment:
      TZ: Asia/Jerusalem

  smtp:
    image: mailu/postfix:1.9
    restart: always
    environment:
      TZ: Asia/Jerusalem

  imap:
    image: mailu/dovecot:1.9
    restart: always
    environment:
      TZ: Asia/Jerusalem

  resolver:
    image: mailu/unbound:1.9
    restart: always
