version: "3.6"

services:
  redis:
    image: redis:alpine
    restart: always

  front:
    image: mailu/nginx:1.9
    restart: always
    env_file: .env
    depends_on:
      - resolver
    labels:
      - "coolify.output.domain=mail.dorbenabu.com"
      - "traefik.enable=true"
      - "traefik.http.routers.mailu.rule=Host(`mail.dorbenabu.com`)"
      - "traefik.http.routers.mailu.entrypoints=web"
      - "traefik.http.routers.mailu.entrypoints=websecure"
      - "traefik.http.routers.mailu.tls=true"
      - "traefik.http.services.mailu.loadbalancer.server.port=80"

  admin:
    image: mailu/admin:1.9
    restart: always
    env_file: .env

  smtp:
    image: mailu/postfix:1.9
    restart: always
    env_file: .env

  imap:
    image: mailu/dovecot:1.9
    restart: always
    env_file: .env

  resolver:
    image: mailu/unbound:1.9
    restart: always
