version: '2'

services:
  front:
    image: ghcr.io/mailu/nginx:1.9
    restart: always
    env_file: .env
    ports:
      - "25:25"
      - "587:587"
      - "143:143"
      - "993:993"
      - "80:80"
      - "443:443"
    volumes:
      - "/mailu/data:/data"
      - "/mailu/certs:/certs"
    depends_on:
      - resolver

  resolver:
    image: ghcr.io/mailu/unbound:1.9
    restart: always

  imap:
    image: ghcr.io/mailu/dovecot:1.9
    restart: always
    env_file: .env
    volumes:
      - "/mailu/data:/data"

  smtp:
    image: ghcr.io/mailu/postfix:1.9
    restart: always
    env_file: .env
    volumes:
      - "/mailu/data:/data"

  admin:
    image: ghcr.io/mailu/admin:1.9
    restart: always
    env_file: .env
    volumes:
      - "/mailu/data:/data"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always