services:
  redis:
    image: redis:alpine
    restart: always

  resolver:
    image: ghcr.io/mailu/unbound:2024.06
    restart: always

  front:
    image: ghcr.io/mailu/nginx:2024.06
    restart: always
    env_file: mailu.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailu.rule=Host(`mail.dorbenabu.com`)"
      - "traefik.http.routers.mailu.entrypoints=web"
      - "traefik.http.services.mailu.loadbalancer.server.port=80"
    depends_on:
      - resolver

  admin:
    image: ghcr.io/mailu/admin:2024.06
    restart: always
    env_file: mailu.env
    depends_on:
      - resolver
      - redis

  smtp:
    image: ghcr.io/mailu/postfix:2024.06
    restart: always
    env_file: mailu.env

  imap:
    image: ghcr.io/mailu/dovecot:2024.06
    restart: always
    env_file: mailu.env
